version: '3.8'

services:
  redis:
    build: ./redis
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app

volumes:
  redis_data:
  ollama_data:
